from app.core.dependencies.audit import AuditDep, AuditLogger, get_audit_logger
from app.core.dependencies.auth import CurrentUser, bearer_scheme, get_current_user, require_roles
from app.core.dependencies.pagination import Pagination, PaginationParams, pagination_params
from app.core.dependencies.roles import (
    AdminOrPatientUser,
    AdminOrReceptionistUser,
    AdminUser,
    BedManagementUser,
    ClinicalStaffUser,
    DoctorUser,
    InventoryViewerUser,
    LabReportEditorUser,
    LabTechOrAdminUser,
    LabTechOrReceptionistUser,
    LabTechUser,
    NurseUser,
    PatientListUser,
    PatientOrReceptionistUser,
    PatientUser,
    PharmacistOrAdminUser,
    PharmacistUser,
    ReceptionistUser,
    StaffNotificationsUser,
    SupplierUser,
)
from app.core.dependencies.settings import SettingsDep, get_settings_dep

__all__ = [
    "AuditDep",
    "AuditLogger",
    "AdminOrPatientUser",
    "AdminOrReceptionistUser",
    "AdminUser",
    "BedManagementUser",
    "ClinicalStaffUser",
    "CurrentUser",
    "DoctorUser",
    "InventoryViewerUser",
    "LabReportEditorUser",
    "LabTechOrAdminUser",
    "LabTechOrReceptionistUser",
    "LabTechUser",
    "NurseUser",
    "Pagination",
    "PaginationParams",
    "PatientListUser",
    "PatientOrReceptionistUser",
    "PatientUser",
    "PharmacistOrAdminUser",
    "PharmacistUser",
    "ReceptionistUser",
    "SettingsDep",
    "StaffNotificationsUser",
    "SupplierUser",
    "bearer_scheme",
    "get_audit_logger",
    "get_current_user",
    "get_settings_dep",
    "pagination_params",
    "require_roles",
]
